---
title: "전통시장 점포 규모와 인구비율에 관한 분석"
author: "이태현"
date: "2024-07-17"
categoty: [project]
jupyter: python3
editor: 
  markdown: 
    wrap: sentence
---

# 분석 목적

전통시장 홍보 목적 가설 : 만약 인구가 많아도 점포수가 적으면 홍보 필요성이 생긴다.
여행 루트에 전통시장을 추가?

2024년에 보도된 [세계타임즈](https://m.thesegye.com/news/view/1065580969734925)에서 KB국민카드의 전통시장 카드 소비 데이터 분석을 볼 수 있습니다.
전통시장의 연령별 매출 비중에서 40%는 60대 이상에서 발생되었습니다.
50대 26%, 40대 17%, 30대 10%, 20대 7%로 연령대가 높을수록 매출 비중이 높게 나타났습니다.

시장은 인구가 많은 곳에 분포되어 있는데, 전통시장 또한 단순히 인구가 많은 곳이 점포수가 많은지?
주 고객층인 60대 이상이 많은 지역에 점포수가 많은지?
알고 싶었다.

2015년 기준으로 60대 이상 비율이 높은 행정구역에 점포수가 많이 분포되어 있는지 분석하기.
이를 바탕으로 60대 비율이 적고, 인구가 많은 수도권, 광역시에 점포수가 많은지?
60대 이상 비율이 높고, 인구가 적은 구역에 점포수가 많은지 비교하기.

#### 나이 나누기

`0~19세 = age_under_20`

`20~59세 = age_2050`

`60~100세 이상 = age_over_60`

한국은 공공기관 및 일부 기업이 60세로 정년으로 두고 있기 때문에 위와 같이 노년의 기준을 60세 이상으로 정했습니다.
미국과 유럽은 60\~65세 사이를 정년으로 두고 있습니다.
그리고

# 점포수 크기에 따른 연령층 확인하기

```{python}
import pandas as pd
import numpy as np
```

#### 2015년 12월 기준 인구조사 파일 불러오기

```{python}
pop = pd.read_excel('data/pop_2015.xlsx')
```

#### 원본 숫자 안에 , 를 없애기 (문자열을 숫자열로 바꾸기)

```{python}
subset = pop.iloc[1:18,1:14]
for col in subset.columns:
    subset[col] = subset[col].str.replace(',', '').astype(int)
subset
```

```{python}
pop.iloc[1:18,1:14] = subset
pop = pop.iloc[0:18,0:14]
pop
```
#### 전국을 제외한 총 인구 그래프화
```{python}
data_pop = pop.drop(0).groupby('행정기관') \
                      .agg(count = ('총 인구수','min'))
data_pop = data_pop.sort_values('count',ascending = False)
data_pop
```
```{python}
import seaborn as sns
import matplotlib.pyplot as plt

plt.rcParams.update({'font.family' : 'Malgun Gothic'})

plt.clf()
sns.barplot(data = data_pop, y = '행정기관', x = 'count', hue = '행정기관')
plt.show()

```
경기도와 서울은 수도권 특성상 면적대비 많은 인구가 몰려있다.
그렇기에 전통시장의 갯수도 많을 수 밖에 없는 조건이므로 나중 분석에서 제외할 예정이다.


#### 각 지역마다 연령층 비율 계산하기

```{python}
pop_서울, pop_부산, pop_대구, pop_인천, pop_광주, pop_대전, pop_울산, pop_세종, \
pop_경기, pop_강원, pop_충북, pop_충남, pop_전북, pop_전남, pop_경북, pop_경남, pop_제주 = [
    pop['총 인구수'][i] for i in range(1, 18)]

서울_유소년_비율 = (pop.iloc[1,3:5].sum()) / pop_서울* 100
부산_유소년_비율 = (pop.iloc[2,3:5].sum()) / pop_부산* 100
대구_유소년_비율 = (pop.iloc[3,3:5].sum()) / pop_대구* 100
인천_유소년_비율 = (pop.iloc[4,3:5].sum()) / pop_인천* 100
광주_유소년_비율 = (pop.iloc[5,3:5].sum()) / pop_광주* 100
대전_유소년_비율 = (pop.iloc[6,3:5].sum()) / pop_대전* 100
울산_유소년_비율 = (pop.iloc[7,3:5].sum()) / pop_울산* 100
세종_유소년_비율 = (pop.iloc[8,3:5].sum()) / pop_세종* 100
경기_유소년_비율 = (pop.iloc[9,3:5].sum()) / pop_경기* 100
강원_유소년_비율 = (pop.iloc[10,3:5].sum()) / pop_강원* 100
충북_유소년_비율 = (pop.iloc[11,3:5].sum()) / pop_충북* 100
충남_유소년_비율 = (pop.iloc[12,3:5].sum()) / pop_충남* 100
전북_유소년_비율 = (pop.iloc[13,3:5].sum()) / pop_전북* 100
전남_유소년_비율 = (pop.iloc[14,3:5].sum()) / pop_전남* 100
경북_유소년_비율 = (pop.iloc[15,3:5].sum()) / pop_경북* 100
경남_유소년_비율 = (pop.iloc[16,3:5].sum()) / pop_경남* 100
제주_유소년_비율 = (pop.iloc[17,3:5].sum()) / pop_제주* 100


서울_성인_비율 = (pop.iloc[1,5:9].sum()) / pop_서울 * 100
부산_성인_비율 = (pop.iloc[2,5:9].sum()) / pop_부산* 100
대구_성인_비율 = (pop.iloc[3,5:9].sum()) / pop_대구* 100
인천_성인_비율 = (pop.iloc[4,5:9].sum()) / pop_인천* 100
광주_성인_비율 = (pop.iloc[5,5:9].sum()) / pop_광주* 100
대전_성인_비율 = (pop.iloc[6,5:9].sum()) / pop_대전* 100
울산_성인_비율 = (pop.iloc[7,5:9].sum()) / pop_울산* 100
세종_성인_비율 = (pop.iloc[8,5:9].sum()) / pop_세종* 100
경기_성인_비율 = (pop.iloc[9,5:9].sum()) / pop_경기* 100
강원_성인_비율 = (pop.iloc[10,5:9].sum()) / pop_강원* 100
충북_성인_비율 = (pop.iloc[11,5:9].sum()) / pop_충북* 100
충남_성인_비율 = (pop.iloc[12,5:9].sum()) / pop_충남* 100
전북_성인_비율 = (pop.iloc[13,5:9].sum()) / pop_전북* 100
전남_성인_비율 = (pop.iloc[14,5:9].sum()) / pop_전남* 100
경북_성인_비율 = (pop.iloc[15,5:9].sum()) / pop_경북* 100
경남_성인_비율 = (pop.iloc[16,5:9].sum()) / pop_경남* 100
제주_성인_비율 = (pop.iloc[17,5:9].sum()) / pop_제주* 100


서울_노인_비율 = (pop.iloc[1,9:14].sum()) / pop_서울 * 100
부산_노인_비율 = (pop.iloc[2,9:14].sum()) / pop_부산* 100
대구_노인_비율 = (pop.iloc[3,9:14].sum()) / pop_대구* 100
인천_노인_비율 = (pop.iloc[4,9:14].sum()) / pop_인천* 100
광주_노인_비율 = (pop.iloc[5,9:14].sum()) / pop_광주* 100
대전_노인_비율 = (pop.iloc[6,9:14].sum()) / pop_대전* 100
울산_노인_비율 = (pop.iloc[7,9:14].sum()) / pop_울산* 100
세종_노인_비율 = (pop.iloc[8,9:14].sum()) / pop_세종* 100
경기_노인_비율 = (pop.iloc[9,9:14].sum()) / pop_경기* 100
강원_노인_비율 = (pop.iloc[10,9:14].sum()) / pop_강원* 100
충북_노인_비율 = (pop.iloc[11,9:14].sum()) / pop_충북* 100
충남_노인_비율 = (pop.iloc[12,9:14].sum()) / pop_충남* 100
전북_노인_비율 = (pop.iloc[13,9:14].sum()) / pop_전북* 100
전남_노인_비율 = (pop.iloc[14,9:14].sum()) / pop_전남* 100
경북_노인_비율 = (pop.iloc[15,9:14].sum()) / pop_경북* 100
경남_노인_비율 = (pop.iloc[16,9:14].sum()) / pop_경남* 100
제주_노인_비율 = (pop.iloc[17,9:14].sum()) / pop_제주* 100
```

#### 인구 비율 DataFrame 만들기

```{python}
pop_ratio = pd.DataFrame({
  '서울'      : [서울_유소년_비율, 서울_성인_비율, 서울_노인_비율],
  '부산'      : [부산_유소년_비율, 부산_성인_비율, 부산_노인_비율],
  '대구'      : [대구_유소년_비율, 대구_성인_비율, 대구_노인_비율],
  '인천'    : [인천_유소년_비율, 인천_성인_비율, 인천_노인_비율],
  '광주'    : [광주_유소년_비율, 광주_성인_비율, 광주_노인_비율],
  '대전'     : [대전_유소년_비율, 대전_성인_비율, 대전_노인_비율],
  '울산'      : [울산_유소년_비율, 울산_성인_비율, 울산_노인_비율],
  '세종'     : [세종_유소년_비율, 세종_성인_비율, 세종_노인_비율],
  '경기도'   : [경기_유소년_비율, 경기_성인_비율, 경기_노인_비율],
  '강원'    : [강원_유소년_비율, 강원_성인_비율, 강원_노인_비율],
  '충청북도'  : [충북_유소년_비율, 충북_성인_비율, 충북_노인_비율],
  '충청남도'  : [충남_유소년_비율, 충남_성인_비율, 충남_노인_비율],
  '전라북도'    : [전북_유소년_비율, 전북_성인_비율, 전북_노인_비율],
  '전라남도'    : [전남_유소년_비율, 전남_성인_비율, 전남_노인_비율],
  '경상북도' : [경북_유소년_비율, 경북_성인_비율, 경북_노인_비율],
  '경상남도' : [경남_유소년_비율, 경남_성인_비율, 경남_노인_비율],
  '제주도'       : [제주_유소년_비율, 제주_성인_비율, 제주_노인_비율]
  })

pop_ratio.index = ['age_under_20','age_2050','age_over_60']
pop_ratio = pop_ratio.transpose()
pop_ratio

```

```{python}
# 지역 칼럼 추가하기
pop_ratio['region'] = ['서울특별시', '부산광역시', '대구광역시', '인천광역시', '광주광역시', '대전광역시', '울산광역시', '세종특별시', '경기도', '강원도', '충청북도', '충청남도', '전라북도', '전라남도', '경상북도', '경상남도', '제주도']

pop_ratio
```

# 전통시장 데이터 불러오기

```{python}
# 데이터 불러오기
market = pd.read_excel("data/traditionalmarket.xlsx")

# 분석을 위한 복사본 만들기
market2 = market.copy()
```

```{python}
# 엑셀의 변수 한글을 영어로 rename
market2 = market2.rename(columns = {"시장명"              : "market_name", 
                                    "시장유형"            : "type",
                                    "소재지도로명주소"    : "adress_road",
                                    "시장개설주기"        : "open_period",
                                    "소재지지번주소"      : "address_old",
                                    "점포수"              : "market_count",
                                    "사용가능상품권"      : "certificate",
                                    "공중화장실 보유여부" :"public_toilet",
                                    "주차장 보유여부"     : "parking_lot",
                                    "개설년도"            : "year",
                                    "데이터기준일자"      : "data_date"})

```

```{python}
# 데이터의 정보 확인하기
market2.describe()
market2["public_toilet"].info()
market2["parking_lot"].info()
market2['market_count'].describe()
```

```{python}
# 점포수에 따른 규모 크기를 설명해주는 변수 만들기
market2 = market2.assign(market_scale = np.where(market2["market_count"] >= 134, "large", 
                                        np.where(market2["market_count"] >= 50, "medium", "small")))

# 편의시설의 유무에 따른 레벨링 하기
market2['level'] = np.where((market2['public_toilet'] == 'Y') & (market2['parking_lot'] == 'Y'), 'high', 
                   np.where((market2['public_toilet'] == 'N') & (market2['public_toilet'] == 'N') , 'low', 'intermediate'))
```

```{python}
# 확인 절차
market2.head()
```

```{python}
# 그래프 그리기
import seaborn as sns
import matplotlib.pyplot as plt

# x축을 편의 시설 레벨
plt.clf()
sns.countplot(data = market2, x = 'level', hue = 'level')
plt.show()
```

```{python}
# 그래프 그리기 위한 df 생성
# 시장 유형와 규모 크기에 따른 그룹화 / 규모 크기 갯수 추가
df = market2.groupby(["type", "market_scale"], as_index = False) \
            .agg(market_count = ("market_scale", "count"))

# 규모 크기에 따른 내림차순
df.sort_values('market_count', ascending = False)

# 만든 df를 x축에 시장 유형, y축은 규모 크기에 따른 점포 갯수
plt.clf()
sns.barplot(data = df, y = 'type', x = 'market_count', hue = 'market_scale')
plt.show()

```

```{python}
plt.clf()

```

```{python}
```

# 인구 데이터와 시장 데이터 합치기

```{python}
market2['region'] = market2['adress_road'].str.split().str[0]

market_pop = pd.merge(market2, pop_ratio, how = 'left', on = 'region')
market_pop
```

# 60대 이상 비율의 계급 나누기

```{python}
market_pop['age_over_60'].describe()
```

중앙값 19.55% 보다 높은 지역을 60대 이상 비율이 많다고 정의

# 시장 종류 갯수

```{python}

# 노인인구 평균 비교
market_pop['under'] = np.where(market_pop['age_over_60'] < 19.55,1,0)
market_pop['over'] = np.where(market_pop['age_over_60'] >= 19.55,1,0)
market_pop.groupby(['region']) \
          .agg(노인인구평균이상 = ('over','sum'), 노인인구평균이하 = ('under','sum'))
    
```
시장 종류가 몇 개인지 알아보기 위해 지역기준으로 1행에서 노인인구 비율이 높으면 1, 2행에서도 노인인구 비율이 낮으면 1의 값을 주어 모두 더하는 방식으로 계산했다.
```{python}
market_pop['over'] = np.where(market_pop['age_over_60'] >= 19.55,1,1)
market_pop.groupby(['region']) \
          .agg(시장종류갯수 = ('over','sum')) \
          .sort_values('시장종류갯수', ascending = False)
```
```{python}
시장종류갯수 = market_pop.groupby(['region']) \
                         .agg(시장종류갯수 = ('over','sum')) \
                         .sort_values('시장종류갯수',ascending = False)

plt.clf()
sns.barplot(data = 시장종류갯수, y = 'region', x = '시장종류갯수', hue = '시장종류갯수')
plt.show()
```
각 지역의 점포수를 sum 해보기

```{python}
#중앙값보다 높고 낮음을 yes | no로 표시하기
market_pop['over'] = np.where(market_pop['age_over_60'] >= 19.55,'Y','N')

over_점포수 = market_pop.groupby(['region','over']) \
                        .agg(count = ('market_count','sum')) \
                        .sort_values('count', ascending = False)
over_점포수
```

```{python}
#서울과 경기도의 인구 비율 고려하기
(pop_서울 + pop_경기) / 51529338 * 100
```
2015년 서울과 경기도의 인구 비율은 43.75% 로 가장 많은 인구가 있다.
인구가 많으면 자연스레 시장의 수도 많은 것은 부정할 수 없는 사실이다.

그래서 이 두 지역을 제외한 나머지 결과를 보았습니다.

```{python}
# 서울과 경기도를 제외한 인구 그래프

plt.clf()
sns.barplot(data = data_pop[2:], y = '행정기관', x = 'count', hue = '행정기관')
plt.show()

```


```{python}
# 인구 많은 지역 제외
over_점포수_new = over_점포수.drop('서울특별시').drop('경기도')
over_점포수_new
```

```{python}
plt.clf()
sns.barplot(data = over_점포수_new, y = 'region', x = 'count', hue = 'over', palette='Set1')
plt.show()
```
상위 5개 중 노인비율이 높은 3곳이 점포수가 많았으며, 노인비율이 낮은 대구, 인천이 4,5위를 하였습니다.

충청도,전라도,강원도와 같은 노인비율이 높은 곳이 다음 순위를 기록하였습니다. 제주도, 3개의 광역시, 세종특별시가 하위권을 기록하였습니다.


```{python}
plt.clf()
sns.barplot(data = data_pop[2:], y = '행정기관', x = 'count', hue = '행정기관')
plt.show()

plt.clf()
sns.barplot(data = over_점포수_new, y = 'region', x = 'count', hue = 'over', palette='Set1')
plt.show()
```
지역 인구수 3위 : 인천광역시가 점포수에서는 5위

지역 인구수 5위 : 대구광역시가 점포수에서는 4위

를 기록하였습니다.

인천은 인구가 많지만 노인인구비율이 적어 점포수에서 하락(???)했습니다.
반대로 대구는 인천보다 인구수가 적지만 경상도의 중심에 있다는 정보를 고려하면 노인인구 비율이 높은 영향을 받아 점포수에서 순위 상승이 있는 것로 판단(????)

인구가 많으면서 노인비율이 높은 부산광역시에서 점포수가 가장 많았습니다.
그리고 인천과 대구 2개의 광역시가 4,5위를 기록했지만 노인인구비율이 높은 도 단위 행정구역이 모두 상단에 위치한다는 점을 알 수 있었습니다.

기본적으로 점포수는 인구수의 영향을 받아 순위가 메겨지는 점은 당연한 사실입니다.
하지만 노인인구비율도 높은 곳이 동시에 점포수가 많다는 점을 알 수 있습니다.


# 점포갯수 / 노인인구
```{python}
# 지역별 노인 인구
서울_노인 = (pop.iloc[1,9:14].sum())
부산_노인 = (pop.iloc[2,9:14].sum())
대구_노인 = (pop.iloc[3,9:14].sum())
인천_노인 = (pop.iloc[4,9:14].sum())
광주_노인 = (pop.iloc[5,9:14].sum())
대전_노인 = (pop.iloc[6,9:14].sum())
울산_노인 = (pop.iloc[7,9:14].sum())
세종_노인 = (pop.iloc[8,9:14].sum())
경기_노인 = (pop.iloc[9,9:14].sum())
강원_노인 = (pop.iloc[10,9:14].sum())
충북_노인 = (pop.iloc[11,9:14].sum())
충남_노인 = (pop.iloc[12,9:14].sum())
전북_노인 = (pop.iloc[13,9:14].sum())
전남_노인 = (pop.iloc[14,9:14].sum())
경북_노인 = (pop.iloc[15,9:14].sum())
경남_노인 = (pop.iloc[16,9:14].sum())
제주_노인 = (pop.iloc[17,9:14].sum())

지역별노인 = pd.DataFrame({
    'region' : ['서울특별시', '부산광역시', '대구광역시', '인천광역시', '광주광역시',
    '대전광역시', '울산광역시', '세종특별시', '경기도', '강원도', '충청북도',
    '충청남도','전라북도','전라남도', '경상북도', '경상남도', '제주도'],
    '노인인구수' : [서울_노인,부산_노인,대구_노인,인천_노인,광주_노인,대전_노인,울산_노인,
                   세종_노인,경기_노인,강원_노인,충북_노인,충남_노인,전북_노인,전남_노인,
                   경북_노인,경남_노인,제주_노인]
                   })
지역별노인 = 지역별노인.sort_values('노인인구수', ascending = False)
지역별노인
```
```{python}
# 시장데이터와 지역별노인 데이터 합치기
market_pop_old = pd.merge(market_pop, 지역별노인, how = 'left', on = 'region')
```
```{python}
ratio_old = market_pop_old.groupby(['region','노인인구수'], as_index = False) \
                          .agg(count = ('market_count','sum')) \
                          .sort_values('count', ascending = False)
ratio_old
```
```{python}
# 점포 수 / 노인인구 수
ratio_old = ratio_old.assign(ratio = ratio_old['count'] / ratio_old['노인인구수'] * 100)
ratio_old = ratio_old.sort_values('ratio',ascending = False)
ratio_old
```
```{python}
plt.clf()
sns.barplot(data = ratio_old, x = 'ratio', y = 'region', hue = 'region')
plt.show()
```


